# @package _global_
batch_size: 32
pin_mem: True
lr: 0.0004
weight_decay: 5.0e-05
max_epochs: 81
nb_epochs_per_weight_save: 10
log_every_n_steps: 2
checkpoint_path:
verbose: 1
load_sparse: False
# Data split and subject choice
seed: 1
partition: [0.99, 0.01]
nb_subjects: -1 # -1 uses all subjects from the train / val dataset.
random: False
random_state: 25
