defaults:
  - _self_
  - augmentations: no_augmentation
  - backbone: ConvNet
  - dataset/STs_schiz_L_strat_bis
  - hydra: no_save
  - mode: classifier
  - model: model
  - platform: cuda
  - projection_head: relu
  - trainer: default
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}